# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoplistapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplist',
            name='uuid',
            field=models.CharField(default='', max_length=40),
        ),
    ]
